name: responsive_website
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.3.1

  # Web Specific
  flutter_web_plugins:
    sdk: flutter
  web: ^0.5.1
  go_router: ^16.3.0
  carousel_slider: ^5.1.1
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  sliver_tools: ^0.2.12

  # Utility Packages
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.2
  url_launcher: ^6.3.2

  # State management
  provider: ^6.1.5+1
  get_it: ^8.2.0

  # Icons
  font_awesome_flutter: ^10.10.0
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/home/hero_section/
    - assets/home/icon/
    - assets/home/projects/